### ISSUE TITLE
 Implicit hierarchies with datetime columns on model relations

### ISSUE THREAD

**Issue by andresgutgon** [t27duck/active_reporting#18]
In this example a `Sale` has a `belongs_to` ActiveRecord relation with `DateDimension`. 
``` ruby
class Sale < ActiveRecord::Base
  belongs_to :placed_at, class_name: 'DateDimension'
end

class SaleFactModel < ActiveReporting::FactModel
  self.measure= :total

  dimension :placed_at
  dimension :item
end

class DateDimensionFactModel < ActiveReporting::FactModel
  default_dimension_label :date

  dimension_hierarchy [:date, :month, :year, :quarter]

  dimension_label_callback :quarter, ->(q) { "Q#{q}" }
end
```
I would like to use [Implicit hierarchies with datetime columns](https://github.com/t27duck/active_reporting#implicit-hierarchies-with-datetime-columns-postgresql-support-only) on date_dimension table through sale fact model.

Something like this:

``` ruby
metric = ActiveReporting::Metric.new(
  :a_metric,
   fact_model: SaleFactModel,
   dimensions: [{ placed_at: :date }]
)
```

I think this is related with [this other PR](https://github.com/t27duck/active_reporting/pull/16) because we could allow pass a configuration object like this:

``` ruby
ActiveReporting::ReportingDimension.new(
  @placed_at_dimension,
   label: :date,
   datetime_hierarchy: month
)
```

What do you think?

**Comment by andresgutgon** [comment]
Please let me know if it's clear the description. Thanks @t27duck

**Comment by t27duck** [comment]
I'm not sure if I completely follow what you're trying to do here.

**Comment by andresgutgon** [comment]
What I'm trying is to use time dimensions but instead in a column in my table in a relationship of that table.

Imagine I have a sessions table that belongs_to user. And that user has a `birthday` datetime column.

I would like to do a report on sessions and use time dimension but on user's 'birthday' column

**Comment by t27duck** [comment]
If you want to try to pull that off, go for it. I personally don't have a use for it at the moment, but that's what open source is about.

**Comment by andresgutgon** [comment]
Great, thanks @t27duck :)

**Comment by germanotm** [comment]
I'am also facing this exact same problem.

I'm trying implement this behavior. I already made a pull request about using datetime hierarchies on mysql, it's the database i use. But i got stuck to make it work through associations, and would appreciate any help.

### My case

On my FactModel table i have the value field i need to measure.
On the Dimension table i have a datetime i need to group by date hierarchies (month, year, etc ...).

### Possible solutions

It already work if the column is in the FactModel. And a test the queries and the same approach will work with joins. Then, is possible change the gem to also accept implicit hierarchical for datetime, even on dimension table.

However when i set a dimension on FactModel it is already classified with :standard type. Thus it will never generate a degenerated_select_statement at select_statment generation. I can`t change this type method because it is defined inside Dimension and not on ReportDimension, it means i don't know if later, the metric will have implicit hierarchical at metric definition.

I thought about implement a similar type method on ReportDimenion, but it started to get really ugly and i aborted this approach.

Other problem is that, at metric definition, i would need to pass a deep level of relation in order to know (dimension, columns and data_trunc). It will completely break the initializer and it leave no clear place to dimension options. Ex

```ruby
my_metric = ActiveReporting :: Metric.new (
  : my_total,
  fact_model: UserFactModel,
  dimensions: [{dimension1: {created_at:: quarter}}]
)
```

I'm thing right now about pass a dimension option called `date_trunc`, that way i can use the regular dimension association to get the output i desire. The metric will be something like:

```ruby
my_metric = ActiveReporting :: Metric.new (
  : my_total,
  fact_model: UserFactModel,
  dimensions: [{dimension1: {field:: created_at, date_trunc: quarter}}]
)
```

Any tips with a smarter way to implementation? I'm not completely satisfied with any of my approaches. The last one seems more promising.

**Comment by t27duck** [comment]
If I had to pick between those options, I'm leaning more to the second one. Perhaps instead of `datetime_hierarchy` the option would just be `hierarchy`? I'd be ok with breaking the API for a semi-major release if needed if it would help clean up the implementation.
